server.port=6080
server.servlet.context-path=/jolserver

#Internal Database URL
spring.datasource.url=jdbc:postgresql://dpg-cv81ccogph6c739977fg-a/joldb_pmas?ssl=true&sslmode=require
spring.datasource.username=admin
spring.datasource.password=xbOUP23pJMNp5JWXNwjyvVXRXyvtdo2z
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.http.encoding.force=true

#jpa not change the case of the name
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

#Send Email
spring.mail.host=smtp.gmail.com
spring.mail.port= 587
spring.mail.protocol=smtp
spring.mail.username=jolboutique12@gmail.com
spring.mail.password=grsizcebobtasvbq
spring.mail.properties.mail.smtp.starttls.enable=true
